# Generated by Django 4.2.16 on 2024-10-14 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Study_Portal_Web", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notes",
            options={"verbose_name": "notes", "verbose_name_plural": "notes"},
        ),
    ]
