# Generated by Django 4.2.16 on 2024-10-23 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Study_Portal_Web", "0002_alter_notes_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notes",
            old_name="User",
            new_name="user",
        ),
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("due", models.DateTimeField()),
                ("is_finished", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
